name       : hunspell-pt
version    : 20161001
release    : 1
source     :
    - http://natura.di.uminho.pt/download/sources/Dictionaries/hunspell/hunspell-pt_PT-20161001.tar.gz : 8777134f4d0bfde6dc175d5f1c721444a98d641a1ce50e95ac2f48fc20a113a0
license    : 
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.1
component  : spelling
summary    : This is a Portuguese (Portugal) dictionary for Hunspell
description: |
    This is a Portuguese (Portugal) dictionary for Hunspell
rundeps    :
    - libhunspell
install    : |
    install -D -m 00644 pt_PT.aff $installdir/usr/share/hunspell/pt_PT.aff
    install -D -m 00644 pt_PT.dic $installdir/usr/share/hunspell/pt_PT.dic
