name       : hunspell-pt
version    : '20171225'
release    : 2
source     :
    - http://natura.di.uminho.pt/download/sources/Dictionaries/hunspell/hunspell-pt_PT-20171225.tar.gz : 07e8e066a40514dbb3705bebe31265cb773e8c0462146eecffee91a8e4c13a88
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : spelling
summary    : This is a Portuguese (Portugal) dictionary for Hunspell
description: |
    This is a Portuguese (Portugal) dictionary for Hunspell
rundeps    :
    - libhunspell
install    : |
    install -D -m 00644 pt_PT.aff $installdir/usr/share/hunspell/pt_PT.aff
    install -D -m 00644 pt_PT.dic $installdir/usr/share/hunspell/pt_PT.dic
