name       : hunspell-pt
version    : '20220621'
release    : 3
source     :
    - https://natura.di.uminho.pt/download/sources/Dictionaries/hunspell/hunspell-pt_PT-20220621.tar.gz : a310abeeb52b706febae0392f44f9541bbfb1b75f3f290c615ade25fa1ccd351
homepage   : https://natura.di.uminho.pt/download/sources/Dictionaries/hunspell/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
summary    : This is a Portuguese (Portugal) dictionary for Hunspell
description: |
    This is a Portuguese (Portugal) dictionary for Hunspell
rundeps    :
    - libhunspell
install    : |
    install -Dm00644 pt_PT.aff $installdir/usr/share/hunspell/pt_PT.aff
    install -Dm00644 pt_PT.dic $installdir/usr/share/hunspell/pt_PT.dic
